//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SME.SMEExportImport {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
    [System.SerializableAttribute()]
    public partial class ServiceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMEExportImport.IWord")]
    public interface IWord {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/ExportWord", ReplyAction="http://tempuri.org/IWord/ExportWordResponse")]
        void ExportWord(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/DocumentExportASCXCreateWord", ReplyAction="http://tempuri.org/IWord/DocumentExportASCXCreateWordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/DocumentExportASCXCreateWordServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string DocumentExportASCXCreateWord(string templateid, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/DocumentExportASCXCreateWordPk", ReplyAction="http://tempuri.org/IWord/DocumentExportASCXCreateWordPkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/DocumentExportASCXCreateWordPkServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string DocumentExportASCXCreateWordPk(string templateid, string regno, string seq, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/DocumentExportASCXCreateExcel", ReplyAction="http://tempuri.org/IWord/DocumentExportASCXCreateExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/DocumentExportASCXCreateExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string DocumentExportASCXCreateExcel(string templateid, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/DocumentExportASCXCreateExcel2", ReplyAction="http://tempuri.org/IWord/DocumentExportASCXCreateExcel2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/DocumentExportASCXCreateExcel2ServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string DocumentExportASCXCreateExcel2(string templateid, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/DocumentUploadASCXReadExcel", ReplyAction="http://tempuri.org/IWord/DocumentUploadASCXReadExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/DocumentUploadASCXReadExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string DocumentUploadASCXReadExcel(string filename, string templateid, string regno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/DocumentUploadASCXReadExcelPensiun", ReplyAction="http://tempuri.org/IWord/DocumentUploadASCXReadExcelPensiunResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/DocumentUploadASCXReadExcelPensiunServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string DocumentUploadASCXReadExcelPensiun(string filename, string templateid, string regno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/Neraca_KMK_KI_SMALLASPXviewExcel", ReplyAction="http://tempuri.org/IWord/Neraca_KMK_KI_SMALLASPXviewExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/Neraca_KMK_KI_SMALLASPXviewExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string Neraca_KMK_KI_SMALLASPXviewExcel(out System.Collections.Generic.Dictionary<string, string> results, string dir, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/Neraca_KMK_KI_SMALLASPXviewExcel_LabaRugi", ReplyAction="http://tempuri.org/IWord/Neraca_KMK_KI_SMALLASPXviewExcel_LabaRugiResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/Neraca_KMK_KI_SMALLASPXviewExcel_LabaRugiServiceDataFaul" +
            "t", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string Neraca_KMK_KI_SMALLASPXviewExcel_LabaRugi(out System.Collections.Generic.Dictionary<string, string> results, string dir, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/Neraca_KMK_KI_MediumASPXViewExcel", ReplyAction="http://tempuri.org/IWord/Neraca_KMK_KI_MediumASPXViewExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/Neraca_KMK_KI_MediumASPXViewExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string Neraca_KMK_KI_MediumASPXViewExcel(out System.Collections.Generic.Dictionary<string, string> results, string dir, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/Neraca_KMK_KI_MediumASPXviewExcel_LabaRugi", ReplyAction="http://tempuri.org/IWord/Neraca_KMK_KI_MediumASPXviewExcel_LabaRugiResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/Neraca_KMK_KI_MediumASPXviewExcel_LabaRugiServiceDataFau" +
            "lt", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string Neraca_KMK_KI_MediumASPXviewExcel_LabaRugi(out System.Collections.Generic.Dictionary<string, string> results, string directori, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/AppraisalNewASPXReadExcel", ReplyAction="http://tempuri.org/IWord/AppraisalNewASPXReadExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/AppraisalNewASPXReadExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string AppraisalNewASPXReadExcel(string filename, string templateid, string regno, string curef, string clseq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainExport_Word", ReplyAction="http://tempuri.org/IWord/CreditProposalMainExport_WordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainExport_WordServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainExport_Word(string regno, string userid, string var_idExport1, string var_idExport2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateNotaWord", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateNotaWordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateNotaWordServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateNotaWord(string regno, string userid, string sessionfullName, string branchName, string ddl_manualSelectedValue, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateNotaExcel", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateNotaExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateNotaExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateNotaExcel(string regno, string userid, string SessionBranchName, string SessionFullName, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateNew", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateNewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateNewServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateNew(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateExist", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateExistResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateExistServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateExist(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateSyarat", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateSyaratResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateSyaratServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateSyarat(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateSyarat2", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateSyarat2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateSyarat2ServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateSyarat2(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateRata", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateRataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateRataServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateRata(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateBank", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateBankResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateBankServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateBank(string regno, string userid, string SessionFullName, string SessionBranchName, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CreditProposalMainp_CreateUrus", ReplyAction="http://tempuri.org/IWord/CreditProposalMainp_CreateUrusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CreditProposalMainp_CreateUrusServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CreditProposalMainp_CreateUrus(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/SPPKExportASPXCreateSPPKWord", ReplyAction="http://tempuri.org/IWord/SPPKExportASPXCreateSPPKWordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/SPPKExportASPXCreateSPPKWordServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string SPPKExportASPXCreateSPPKWord(out System.Collections.Generic.Dictionary<string, string> result, string regno, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CustomerInfoExportASPXExport_Excel", ReplyAction="http://tempuri.org/IWord/CustomerInfoExportASPXExport_ExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CustomerInfoExportASPXExport_ExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CustomerInfoExportASPXExport_Excel(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CustomerInfoExportASPXExport_Word", ReplyAction="http://tempuri.org/IWord/CustomerInfoExportASPXExport_WordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CustomerInfoExportASPXExport_WordServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CustomerInfoExportASPXExport_Word(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CBICustomerInfoExportASPXExport_Excel", ReplyAction="http://tempuri.org/IWord/CBICustomerInfoExportASPXExport_ExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CBICustomerInfoExportASPXExport_ExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CBICustomerInfoExportASPXExport_Excel(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/CBICustomerInfoExportASPXExport_Word", ReplyAction="http://tempuri.org/IWord/CBICustomerInfoExportASPXExport_WordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/CBICustomerInfoExportASPXExport_WordServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string CBICustomerInfoExportASPXExport_Word(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWord/ChannellingInitialDataEntryUploadExcel", ReplyAction="http://tempuri.org/IWord/ChannellingInitialDataEntryUploadExcelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SME.SMEExportImport.ServiceData), Action="http://tempuri.org/IWord/ChannellingInitialDataEntryUploadExcelServiceDataFault", Name="ServiceData", Namespace="http://schemas.datacontract.org/2004/07/SMEExportImportService")]
        string ChannellingInitialDataEntryUploadExcel(string filePath, string apRegno, string aaNo, string productId, string prodSeq, string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordChannel : SME.SMEExportImport.IWord, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordClient : System.ServiceModel.ClientBase<SME.SMEExportImport.IWord>, SME.SMEExportImport.IWord {
        
        public WordClient() {
        }
        
        public WordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExportWord(string name) {
            base.Channel.ExportWord(name);
        }
        
        public string DocumentExportASCXCreateWord(string templateid, string regno, string userid) {
            return base.Channel.DocumentExportASCXCreateWord(templateid, regno, userid);
        }
        
        public string DocumentExportASCXCreateWordPk(string templateid, string regno, string seq, string userid) {
            return base.Channel.DocumentExportASCXCreateWordPk(templateid, regno, seq, userid);
        }
        
        public string DocumentExportASCXCreateExcel(string templateid, string regno, string userid) {
            return base.Channel.DocumentExportASCXCreateExcel(templateid, regno, userid);
        }
        
        public string DocumentExportASCXCreateExcel2(string templateid, string regno, string userid) {
            return base.Channel.DocumentExportASCXCreateExcel2(templateid, regno, userid);
        }
        
        public string DocumentUploadASCXReadExcel(string filename, string templateid, string regno) {
            return base.Channel.DocumentUploadASCXReadExcel(filename, templateid, regno);
        }
        
        public string DocumentUploadASCXReadExcelPensiun(string filename, string templateid, string regno) {
            return base.Channel.DocumentUploadASCXReadExcelPensiun(filename, templateid, regno);
        }
        
        public string Neraca_KMK_KI_SMALLASPXviewExcel(out System.Collections.Generic.Dictionary<string, string> results, string dir, string regno, string userid) {
            return base.Channel.Neraca_KMK_KI_SMALLASPXviewExcel(out results, dir, regno, userid);
        }
        
        public string Neraca_KMK_KI_SMALLASPXviewExcel_LabaRugi(out System.Collections.Generic.Dictionary<string, string> results, string dir, string regno, string userid) {
            return base.Channel.Neraca_KMK_KI_SMALLASPXviewExcel_LabaRugi(out results, dir, regno, userid);
        }
        
        public string Neraca_KMK_KI_MediumASPXViewExcel(out System.Collections.Generic.Dictionary<string, string> results, string dir, string regno, string userid) {
            return base.Channel.Neraca_KMK_KI_MediumASPXViewExcel(out results, dir, regno, userid);
        }
        
        public string Neraca_KMK_KI_MediumASPXviewExcel_LabaRugi(out System.Collections.Generic.Dictionary<string, string> results, string directori, string regno, string userid) {
            return base.Channel.Neraca_KMK_KI_MediumASPXviewExcel_LabaRugi(out results, directori, regno, userid);
        }
        
        public string AppraisalNewASPXReadExcel(string filename, string templateid, string regno, string curef, string clseq) {
            return base.Channel.AppraisalNewASPXReadExcel(filename, templateid, regno, curef, clseq);
        }
        
        public string CreditProposalMainExport_Word(string regno, string userid, string var_idExport1, string var_idExport2) {
            return base.Channel.CreditProposalMainExport_Word(regno, userid, var_idExport1, var_idExport2);
        }
        
        public string CreditProposalMainp_CreateNotaWord(string regno, string userid, string sessionfullName, string branchName, string ddl_manualSelectedValue, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateNotaWord(regno, userid, sessionfullName, branchName, ddl_manualSelectedValue, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue);
        }
        
        public string CreditProposalMainp_CreateNotaExcel(string regno, string userid, string SessionBranchName, string SessionFullName, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateNotaExcel(regno, userid, SessionBranchName, SessionFullName, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateNew(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateNew(regno, userid, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateExist(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateExist(regno, userid, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateSyarat(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateSyarat(regno, userid, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateSyarat2(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateSyarat2(regno, userid, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateRata(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateRata(regno, userid, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateBank(string regno, string userid, string SessionFullName, string SessionBranchName, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateBank(regno, userid, SessionFullName, SessionBranchName, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string CreditProposalMainp_CreateUrus(string regno, string userid, string DDL_FORMAT_TYPESelectedValue, string DDL_KETENTUANSelectedValue, string ddl_manualSelectedValue) {
            return base.Channel.CreditProposalMainp_CreateUrus(regno, userid, DDL_FORMAT_TYPESelectedValue, DDL_KETENTUANSelectedValue, ddl_manualSelectedValue);
        }
        
        public string SPPKExportASPXCreateSPPKWord(out System.Collections.Generic.Dictionary<string, string> result, string regno, string userid) {
            return base.Channel.SPPKExportASPXCreateSPPKWord(out result, regno, userid);
        }
        
        public string CustomerInfoExportASPXExport_Excel(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue) {
            return base.Channel.CustomerInfoExportASPXExport_Excel(regno, userid, curef, DDL_FORMATFILESelectedValue);
        }
        
        public string CustomerInfoExportASPXExport_Word(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue) {
            return base.Channel.CustomerInfoExportASPXExport_Word(regno, userid, curef, DDL_FORMATFILESelectedValue);
        }
        
        public string CBICustomerInfoExportASPXExport_Excel(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue) {
            return base.Channel.CBICustomerInfoExportASPXExport_Excel(regno, userid, curef, DDL_FORMATFILESelectedValue);
        }
        
        public string CBICustomerInfoExportASPXExport_Word(string regno, string userid, string curef, string DDL_FORMATFILESelectedValue) {
            return base.Channel.CBICustomerInfoExportASPXExport_Word(regno, userid, curef, DDL_FORMATFILESelectedValue);
        }
        
        public string ChannellingInitialDataEntryUploadExcel(string filePath, string apRegno, string aaNo, string productId, string prodSeq, string userId) {
            return base.Channel.ChannellingInitialDataEntryUploadExcel(filePath, apRegno, aaNo, productId, prodSeq, userId);
        }
    }
}
