//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SME.DCM {
    
    
    public partial class CollateralDetailData {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// TXT_ID_AGUNAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_ID_AGUNAN;
        
        /// <summary>
        /// TXT_JENIS_AGUNAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_JENIS_AGUNAN;
        
        /// <summary>
        /// TXT_KETERANGAN_AGUNAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_KETERANGAN_AGUNAN;
        
        /// <summary>
        /// TXT_ERRORMSG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_ERRORMSG;
        
        /// <summary>
        /// DDL_SIFAT_AGUNAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_SIFAT_AGUNAN;
        
        /// <summary>
        /// TXT_NAMA_PEMILIK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_NAMA_PEMILIK;
        
        /// <summary>
        /// DDL_BUKTI_KEPEMILIKAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_BUKTI_KEPEMILIKAN;
        
        /// <summary>
        /// DDL_STATUS_KEPEMILIKAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_STATUS_KEPEMILIKAN;
        
        /// <summary>
        /// TXT_TGL_TERBIT_SERTIFIKAT_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_TERBIT_SERTIFIKAT_DD;
        
        /// <summary>
        /// DDL_TGL_TERBIT_SERTIFIKAT_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_TERBIT_SERTIFIKAT_MM;
        
        /// <summary>
        /// TXT_TGL_TERBIT_SERTIFIKAT_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_TERBIT_SERTIFIKAT_YY;
        
        /// <summary>
        /// TXT_TGL_EXPIRED_SERTIFIKAT_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_EXPIRED_SERTIFIKAT_DD;
        
        /// <summary>
        /// DDL_TGL_EXPIRED_SERTIFIKAT_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_EXPIRED_SERTIFIKAT_MM;
        
        /// <summary>
        /// TXT_TGL_EXPIRED_SERTIFIKAT_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_EXPIRED_SERTIFIKAT_YY;
        
        /// <summary>
        /// TXT_ALAMAT_AGUNAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_ALAMAT_AGUNAN;
        
        /// <summary>
        /// DDL_LOKASI_DATI2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_LOKASI_DATI2;
        
        /// <summary>
        /// DDL_CURRENCY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_CURRENCY;
        
        /// <summary>
        /// TXT_NILAI_PASAR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_NILAI_PASAR;
        
        /// <summary>
        /// TXT_NILAI_APPRAISAL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_NILAI_APPRAISAL;
        
        /// <summary>
        /// TXT_NILAI_LIKUIDASI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_NILAI_LIKUIDASI;
        
        /// <summary>
        /// TXT_NILAI_NJOP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_NILAI_NJOP;
        
        /// <summary>
        /// TXT_NILAI_PENGIKATAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_NILAI_PENGIKATAN;
        
        /// <summary>
        /// TXT_TGL_PENILAIAN_PERTAMA_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENILAIAN_PERTAMA_DD;
        
        /// <summary>
        /// DDL_TGL_PENILAIAN_PERTAMA_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_PENILAIAN_PERTAMA_MM;
        
        /// <summary>
        /// TXT_TGL_PENILAIAN_PERTAMA_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENILAIAN_PERTAMA_YY;
        
        /// <summary>
        /// TXT_TGL_PENILAIAN_TERAKHIR_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENILAIAN_TERAKHIR_DD;
        
        /// <summary>
        /// DDL_TGL_PENILAIAN_TERAKHIR_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_PENILAIAN_TERAKHIR_MM;
        
        /// <summary>
        /// TXT_TGL_PENILAIAN_TERAKHIR_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENILAIAN_TERAKHIR_YY;
        
        /// <summary>
        /// DDL_PENILAIAN_OLEH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_PENILAIAN_OLEH;
        
        /// <summary>
        /// DDL_JENIS_PENGIKATAN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_JENIS_PENGIKATAN;
        
        /// <summary>
        /// TXT_TGL_PENGIKATAN_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENGIKATAN_DD;
        
        /// <summary>
        /// DDL_TGL_PENGIKATAN_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_PENGIKATAN_MM;
        
        /// <summary>
        /// TXT_TGL_PENGIKATAN_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENGIKATAN_YY;
        
        /// <summary>
        /// DDL_ASURANSI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_ASURANSI;
        
        /// <summary>
        /// TXT_PERINGKAT_SURAT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_PERINGKAT_SURAT;
        
        /// <summary>
        /// TXT_TGL_PERINGKAT_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PERINGKAT_DD;
        
        /// <summary>
        /// DDL_TGL_PERINGKAT_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_PERINGKAT_MM;
        
        /// <summary>
        /// TXT_TGL_PERINGKAT_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PERINGKAT_YY;
        
        /// <summary>
        /// TXT_PENERBIT_SURAT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_PENERBIT_SURAT;
        
        /// <summary>
        /// TXT_TGL_PENERBITAN_SURAT_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENERBITAN_SURAT_DD;
        
        /// <summary>
        /// DDL_TGL_PENERBITAN_SURAT_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_PENERBITAN_SURAT_MM;
        
        /// <summary>
        /// TXT_TGL_PENERBITAN_SURAT_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_PENERBITAN_SURAT_YY;
        
        /// <summary>
        /// TXT_TGL_EXPIRED_SURAT_DD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_EXPIRED_SURAT_DD;
        
        /// <summary>
        /// DDL_TGL_EXPIRED_SURAT_MM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_TGL_EXPIRED_SURAT_MM;
        
        /// <summary>
        /// TXT_TGL_EXPIRED_SURAT_YY control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TXT_TGL_EXPIRED_SURAT_YY;
        
        /// <summary>
        /// BTN_SAVE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BTN_SAVE;
        
        /// <summary>
        /// BTN_UPDATE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BTN_UPDATE;
    }
}
